# Generated by Django 5.2.7 on 2025-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_height_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
