# Generated by Django 5.2.7 on 2025-10-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='height',
            new_name='Batch',
        ),
    ]
